### ISSUE TITLE
Maven Central Issue

### ISSUE THREAD

**Issue by melloware** [adminfaces/quarkus-omnifaces#16]
When I try and use Quarkus OmniFaces it fails with...

```
Could not resolve dependencies for project org.primefaces.extensions:showcase:war:10.0.0-SNAPSHOT: Failed to collect dependencies at com.github.adminfaces:quarkus-omnifaces:jar:1.0.1: Failed to read artifact descriptor for com.github.adminfaces:quarkus-omnifaces:jar:1.0.1: Could not find artifact com.github.adminfaces:quarkus-omnifaces-parent:pom:1.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

And I verified the parent pom is not in Maven Central: https://search.maven.org/search?q=com.github.adminfaces

**Comment by rmpestano** [comment]
You're right, we just released the runtime jar, we still need to release parent and deployment. I just released missing artifacts for 1.0.1, please test again in a couple of hours.

Thank you!

**Comment by rmpestano** [comment]
Looks like it didn't sync with central because the release was closed, I'll release 1.1.0 shortly so let's see if it fixes the problem

**Comment by melloware** [comment]
Thank 1.1.0 is in Maven Central and now works properly!

**Comment by rmpestano** [comment]
Awesome, thank you!
