### ISSUE TITLE
Remove CombinedResourceHandler?

### ISSUE THREAD

**Issue by melloware** [adminfaces/quarkus-omnifaces#26]
I was wondering why you chose to enforce the CombinedResourceHandler in this extension and not let users decide in their own faces-config.xml?

**Comment by rmpestano** [comment]
Hi @melloware,

Do you have issues with it? maybe we can enable/disable via [property here](https://github.com/adminfaces/quarkus-omnifaces/blob/4169de378e39cc8e0f65395e0f7c529a983a6f15/deployment/src/main/java/io/quarkus/omnifaces/deployment/OmniFacesProcessor.java#L84), WDYT?

**Comment by melloware** [comment]
In an app I was converting to quarkus OmniFaces was saying two handlers were declared. I thought it might have been a bug but then realized you had it in this jar and I already had it in my faces config.

**Comment by rmpestano** [comment]
I see, so let's just remove It from the extension

**Comment by melloware** [comment]
I think that is a good idea

**Comment by rmpestano** [comment]
Let me know if the latest fix your problem and then we can release

**Comment by melloware** [comment]
Yep it does!

**Comment by rmpestano** [comment]
It should be in central in next hours, thank you!

**Comment by melloware** [comment]
@rmpestano I thought you would be interested in this project I did where I take the PF showcase and run it on Wildfly EE vs Quarkus and compare the results. I then layer on top a bunch of JSF Optimizations and the numbers for the client get even more impressive.

https://github.com/melloware/quarkus-faces
