### ISSUE TITLE
Upgrade to Quarkus 1.13

### ISSUE THREAD

**Issue by melloware** [adminfaces/quarkus-omnifaces#44]
Quarkus 1.13 changed some classes on how to register. Submitting a PR following how MyFaces did it.

**Comment by melloware** [comment]
@rmpestano any chance of getting this merged and a a new version on Maven Central?

**Comment by rmpestano** [comment]
Hi @melloware, I'll try to do this weekend, we need to release from gh-actions now because bintray is gone

**Comment by rmpestano** [comment]
quarkus-omnifaces `1.4.0` should be on maven central in soon

**Comment by melloware** [comment]
Many thanks I just updated my Quarkus Faces showcase and everything is working with your new JAR and Quarkus 1.13.7
