### ISSUE TITLE
@Param

### ISSUE THREAD

**Issue by melloware** [adminfaces/quarkus-omnifaces#82]
See: https://github.com/omnifaces/omnifaces/issues/658

I'm trying to port the JSF app to quarkus. I use @param in my beans, it works OK in WildFly. I am able to compile it, however during the startup I am getting "[1] Unsatisfied dependency for type java.lang.Integer and qualifiers [@param]".

**Comment by melloware** [comment]
Closing for: https://github.com/quarkiverse/quarkus-omnifaces/issues/3

**Comment by rmpestano** [comment]
Nice initiative @melloware 👍 watching closely and will help if I can

**Comment by melloware** [comment]
@rmpestano i wonder if you should mark this repo as "Archived" in settings and post a link in the README.MD to the new official Quarkiverse plugin?
